[TASK] Separate language keys of BE templates
The backend list view uses its own
entries from `locallang.xlf` which are namespaced.

EXCEPTION: The entries for status of shipping and
payment are still shared. But it's unlikely that
developer might want to change them.